const PRINTER_MODELS = [
  { id: "bambu_a1_mini", name: "Bambu A1 Mini", provider: "Bambu Lab", image: "https://picsum.photos/seed/bambu-a1-mini/200/200" },
  { id: "bambu_a1", name: "Bambu A1", provider: "Bambu Lab", image: "https://picsum.photos/seed/bambu-a1/200/200" },
  { id: "bambu_x1_carbon", name: "Bambu Lab X1 Carbon", provider: "Bambu Lab", image: "https://picsum.photos/seed/bambu-x1/200/200" },
  { id: "bambu_p1s", name: "Bambu Lab P1S", provider: "Bambu Lab", image: "https://picsum.photos/seed/bambu-p1s/200/200" },
  { id: "bambu_p1p", name: "Bambu Lab P1P", provider: "Bambu Lab", image: "https://picsum.photos/seed/bambu-p1p/200/200" },
  { id: "prusa_mk3s", name: "Prusa MK3S+", provider: "Prusa Research", image: "https://picsum.photos/seed/prusa-mk3s/200/200" },
  { id: "prusa_mk4", name: "Prusa MK4", provider: "Prusa Research", image: "https://picsum.photos/seed/prusa-mk4/200/200" },
  { id: "prusa_mini", name: "Prusa Mini", provider: "Prusa Research", image: "https://picsum.photos/seed/prusa-mini/200/200" },
  { id: "ender_3_v2", name: "Creality Ender 3 V2", provider: "Creality", image: "https://picsum.photos/seed/ender3v2/200/200" },
  { id: "ender_3_v3", name: "Creality Ender 3 V3", provider: "Creality", image: "https://picsum.photos/seed/ender3v3/200/200" },
  { id: "ender_5", name: "Creality Ender 5", provider: "Creality", image: "https://picsum.photos/seed/ender5/200/200" },
  { id: "creality_k1", name: "Creality K1", provider: "Creality", image: "https://picsum.photos/seed/creality-k1/200/200" },
  { id: "creality_k1_max", name: "Creality K1 Max", provider: "Creality", image: "https://picsum.photos/seed/creality-k1max/200/200" },
  { id: "qi_di_x_max_3", name: "Qi DI X-Max 3", provider: "Qi DI", image: "https://picsum.photos/seed/qidi-xmax3/200/200" },
  { id: "qidi_q1_pro", name: "Qidi Q1 Pro", provider: "Qidi Tech", image: "https://picsum.photos/seed/qidi-q1pro/200/200" },
  { id: "qidi_tech_x", name: "Qidi Tech X-Max", provider: "Qidi Tech", image: "https://picsum.photos/seed/qidi-xmax/200/200" },
  { id: "anycubic_kobra", name: "Anycubic Kobra 2", provider: "Anycubic", image: "https://picsum.photos/seed/anycubic-kobra/200/200" },
  { id: "anycubic_mega_s", name: "Anycubic Mega-S", provider: "Anycubic", image: "https://picsum.photos/seed/anycubic-megas/200/200" },
  { id: "flashforge_finder", name: "Flashforge Finder 3", provider: "Flashforge", image: "https://picsum.photos/seed/flashforge-finder/200/200" },
  { id: "flashforge_adventurer", name: "Flashforge Adventurer 5M", provider: "Flashforge", image: "https://picsum.photos/seed/flashforge-adventurer/200/200" },
  { id: "artillery_sidewinder", name: "Artillery Sidewinder X2", provider: "Artillery", image: "https://picsum.photos/seed/artillery-sidewinder/200/200" },
  { id: "artillery_genius", name: "Artillery Genius Pro", provider: "Artillery", image: "https://picsum.photos/seed/artillery-genius/200/200" },
  { id: "ultimaker_s3", name: "Ultimaker S3", provider: "Ultimaker", image: "https://picsum.photos/seed/ultimaker-s3/200/200" },
  { id: "ultimaker_s5", name: "Ultimaker S5", provider: "Ultimaker", image: "https://picsum.photos/seed/ultimaker-s5/200/200" },
  { id: "formlabs_form3", name: "Formlabs Form 3+", provider: "Formlabs", image: "https://picsum.photos/seed/formlabs-form3/200/200" },
  { id: "lulzbot_mini", name: "LulzBot Mini", provider: "LulzBot", image: "https://picsum.photos/seed/lulzbot-mini/200/200" },
  { id: "lulzbot_taz", name: "LulzBot TAZ Pro", provider: "LulzBot", image: "https://picsum.photos/seed/lulzbot-taz/200/200" },
  { id: "raise3d_pro2", name: "Raise3D Pro2 Plus", provider: "Raise3D", image: "https://picsum.photos/seed/raise3d-pro2/200/200" },
  { id: "raise3d_e2", name: "Raise3D E2", provider: "Raise3D", image: "https://picsum.photos/seed/raise3d-e2/200/200" },
  { id: "sindoh_3dwox", name: "Sindoh 3D Wox", provider: "Sindoh", image: "https://picsum.photos/seed/sindoh-3dwox/200/200" },
  { id: "snapmaker_a350", name: "Snapmaker A350T", provider: "Snapmaker", image: "https://picsum.photos/seed/snapmaker-a350/200/200" },
  { id: "monoprice_select", name: "Monoprice Select Mini V2", provider: "Monoprice", image: "https://picsum.photos/seed/monoprice-select/200/200" },
  { id: "wanhao_d7", name: "Wanhao D7", provider: "Wanhao", image: "https://picsum.photos/seed/wanhao-d7/200/200" },
  { id: "craftbot_plus", name: "CraftBot Plus", provider: "CraftBot", image: "https://picsum.photos/seed/craftbot-plus/200/200" },
  { id: "bcn3d_sigmax", name: "BCN3D Sigmax R19", provider: "BCN3D", image: "https://picsum.photos/seed/bcn3d-sigmax/200/200" },
  { id: "homemade_custom", name: "Custom / DIY", provider: "Community", image: "https://picsum.photos/seed/custom-diy/200/200" },
];

export default PRINTER_MODELS;
